; folds.scm — Foldable regions for Hew

[
  (block)
  (function_declaration)
  (async_function_declaration)
  (gen_function_declaration)
  (async_gen_function_declaration)
  (struct_declaration)
  (enum_declaration)
  (trait_declaration)
  (impl_declaration)
  (actor_declaration)
  (supervisor_declaration)
  (wire_declaration)
  (extern_block)
  (receive_function)
  (receive_gen_function)
  (if_expression)
  (match_expression)
  (select_expression)
  (join_expression)
  (race_expression)
  (try_catch_expression)
] @fold
